; =============================================================
; PHP config para es21plus
; @author Carlos Vico
; =============================================================

; Asegura que $_ENV se rellene desde el entorno del contenedor Docker
variables_order = "EGPCS"

; Encoding UTF-8
default_charset = "UTF-8"

; Mostrar errores en desarrollo
display_errors = On
error_reporting = E_ALL
