-- Relleno de campos nuevos + corrección de encoding para productos existentes
-- @author Carlitos6712
SET NAMES utf8mb4;

-- ── CORREGIR NOMBRES CON ENCODING ROTO ───────────────────────────────────────
UPDATE productos SET nombre='Líquido de frenos Castrol React DOT 4' WHERE id=43;
UPDATE productos SET nombre='Líquido de frenos Motul DOT 5.1' WHERE id=44;
UPDATE productos SET nombre='Kit revisión bomba freno delantera' WHERE id=47;
UPDATE productos SET nombre='Bujía NGK CR9EK estándar' WHERE id=56;
UPDATE productos SET nombre='Bujía Denso IU22 Iridium Power' WHERE id=57;
UPDATE productos SET nombre='Correa distribución Gates Honda CBF 125' WHERE id=59;
UPDATE productos SET nombre='Válvula admisión Vespa GTS 125' WHERE id=61;
UPDATE productos SET nombre='Kit transmisión Yamaha MT-07 2014-2020' WHERE id=67;
UPDATE productos SET nombre='Kit transmisión Kawasaki Z900 2017-2022' WHERE id=68;
UPDATE productos SET nombre='Piñón delantero JT 16T paso 525' WHERE id=71;
UPDATE productos SET nombre='Tensor cadena automático universal' WHERE id=72;
UPDATE productos SET nombre='Eslabón de unión rápida DID 520 Gold' WHERE id=73;
UPDATE productos SET nombre='Eslabón de unión rápida RK 525' WHERE id=74;
UPDATE productos SET nombre='Batería Yuasa YTX9-BS 12V 8Ah' WHERE id=77;
UPDATE productos SET nombre='Batería Bosch M6 YTZ14S 12V 11.2Ah' WHERE id=78;
UPDATE productos SET nombre='Cargador batería Optimate 4 Dual' WHERE id=79;
UPDATE productos SET nombre='Relé arranque universal 12V 30A' WHERE id=84;
UPDATE productos SET nombre='Sensor posición cigüeñal Suzuki GSX-R1000' WHERE id=86;
UPDATE productos SET nombre='Cable bujía NGK Racing RC-YM803 set 4' WHERE id=88;
UPDATE productos SET nombre='Puños manillar Oxford Primo espuma' WHERE id=97;
UPDATE productos SET nombre='Puños calefactables Oxford Hot Grips Essential' WHERE id=98;
UPDATE productos SET nombre='Protector depósito resina epoxi universal' WHERE id=99;
UPDATE productos SET nombre='Tapa depósito CNC Ducati Monster 821/1200' WHERE id=100;
UPDATE productos SET nombre='Tornillería carenado kit acero inox 30 piezas' WHERE id=103;

-- ── FRENOS (Estante A) ────────────────────────────────────────────────────────
UPDATE productos SET marca='Brembo',      codigo_barras='8020584046904', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-1', descripcion_larga='Pastilla sinterizada para disco delantero. Compuesto metálico de alta fricción. Compatible con mordazas Brembo P4 y P34. Temperatura: 50–650 °C. Incluye muelle anti-vibración y pasadores de retención.' WHERE id=1;
UPDATE productos SET marca='Galfer',      codigo_barras='8427480001234', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-2', descripcion_larga='Disco flotante Wave 310 mm. Acero inoxidable 420C. Absorbe dilatación térmica y reduce transferencia de calor. Compatible con mordazas radiales estándar. Hasta 30% menos peso que disco macizo.' WHERE id=2;
UPDATE productos SET marca='Brembo',      codigo_barras='8020584049301', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-1', descripcion_larga='Pastilla Brembo SC Strada Corsa. Compuesto cerámico para uso mixto calle/circuito. Muy bajo desgaste y excelente modulación. Temperatura: 0–550 °C. Incluye sensor de desgaste.' WHERE id=39;
UPDATE productos SET marca='EBC Brakes',  codigo_barras='0841336034289', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-1', descripcion_larga='Pastilla trasera EBC FA69 compuesto orgánico. Frenadas suaves y progresivas para calle. Mínimo polvo y ruido. Compatible con múltiples modelos japoneses. Temperatura: 50–400 °C.' WHERE id=40;
UPDATE productos SET marca='Galfer',      codigo_barras='8427480001357', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-2', descripcion_larga='Disco flotante Galfer Wave 320 mm. Diseño ondulado para mejor evacuación del calor. Acero inoxidable 420C. Compatible con horquillas invertidas 43 mm y mordazas radiales. Homologado CE.' WHERE id=41;
UPDATE productos SET marca='Galfer',      codigo_barras='8427480001401', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-2', descripcion_larga='Disco trasero Galfer 240 mm acero inoxidable 420C. Perforado para evacuación de gases. Acabado mecanizado en la estrella. Apto para uso mixto calle/pista.' WHERE id=42;
UPDATE productos SET marca='Castrol',     codigo_barras='5010231503842', proveedor='Europarts Iberia SA',         ubicacion='Estante A-3', descripcion_larga='Líquido de frenos sintético DOT 4 Castrol React. Punto ebullición seco: 265 °C. Húmedo: 180 °C. Compatible con sistemas ABS. 500 ml. Cambio cada 2 años o 30.000 km.' WHERE id=43;
UPDATE productos SET marca='Motul',       codigo_barras='3374650008028', proveedor='Europarts Iberia SA',         ubicacion='Estante A-3', descripcion_larga='Líquido de frenos DOT 5.1 Motul. Punto ebullición seco: 270 °C. Húmedo: 190 °C. Muy baja viscosidad para respuesta óptima en sistemas ABS y control de tracción. 500 ml.' WHERE id=44;
UPDATE productos SET marca='Genérico',    codigo_barras='8412345100451', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-4', descripcion_larga='Cable freno delantero universal 120 cm. Funda exterior acero trenzado, alma acero galvanizado. Extremos con niples estándar 8 y 6 mm.' WHERE id=45;
UPDATE productos SET marca='Brembo',      codigo_barras='8020584215101', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-2', descripcion_larga='Pinza monobloc Brembo P4 30/34 aluminio mecanizado. 4 pistones 30 y 34 mm. Montaje axial. Requiere disco 310–320 mm. Incluye pastillas SA estándar. Peso: 740 g.' WHERE id=46;
UPDATE productos SET marca='Genérico',    codigo_barras='8412345100529', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-4', descripcion_larga='Kit revisión bomba freno delantera radial. Incluye émbolos, retenes, muelles y tornillería. Compatible con bombas Brembo RCS 15/17/19. Revisión cada 50.000 km.' WHERE id=47;
UPDATE productos SET marca='Venhill',     codigo_barras='5055695019017', proveedor='MotoDistribución Ibérica SL', ubicacion='Estante A-4', descripcion_larga='Par latiguillos freno acero trenzado inoxidable. Funda nylon trenzado, racores aluminio anodizado. Eliminan elasticidad del goma convencional. Homologados para vía pública.' WHERE id=48;

-- ── MOTOR (Estante B) ─────────────────────────────────────────────────────────
UPDATE productos SET marca='HiFlo Filtro', codigo_barras='5055578004519', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro aceite HiFlo para Honda. Núcleo acero anti-corrosión. Papel filtrante 17 µm. Válvula anti-retorno integrada. Equivalente Honda 15410-MFJ-D02. Cambiar en cada cambio de aceite.' WHERE id=3;
UPDATE productos SET marca='NGK',          codigo_barras='0070043253756', proveedor='Europarts Iberia SA', ubicacion='Estante B-2', descripcion_larga='Bujía iridio NGK CR8EIX. Electrodo central iridio 0,6 mm para mejor encendido y menor consumo. Compatible con motores 4T 250–600 cc. Vida útil: 60.000 km.' WHERE id=4;
UPDATE productos SET marca='Motul',        codigo_barras='3374650096330', proveedor='Europarts Iberia SA', ubicacion='Estante B-3', descripcion_larga='Aceite 100% sintético Motul 300V Factory Line 10W-40. Doble ester para máxima protección. JASO MA2, API SN. Protege embrague húmedo y seco. 1 litro. Para motores de competición.' WHERE id=5;
UPDATE productos SET marca='HiFlo Filtro', codigo_barras='5055578004922', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro aceite HiFlo Yamaha R6/R1. Compatible: YZF-R6 2003–2020, YZF-R1 2004–2014. Bypass valve 1 bar. Filtración 17 µm. Sustituye Yamaha 5GH-13440-50.' WHERE id=49;
UPDATE productos SET marca='HiFlo Filtro', codigo_barras='5055578004601', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro aceite Hiflofiltro Honda CBR600RR 2003–2020 y CBR1000RR 2004–2019. Filtración 17 µm. Gasket NBR resistente a aceites sintéticos.' WHERE id=50;
UPDATE productos SET marca='K&N',          codigo_barras='0024844012747', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro aire alto flujo K&N Kawasaki ZX-6R. Algodón 4 capas. Lavable y reutilizable hasta 1.000.000 km. Aumenta caudal de aire hasta un 50%. Compatible con caja de filtro estándar.' WHERE id=51;
UPDATE productos SET marca='Twin Air',     codigo_barras='8711435901016', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro aire espuma Twin Air universal 340x420 mm. 2 capas de microfiltrado. Lavable con limpiador Twin Air. Recortable para ajustar a cualquier caja de filtro. Pre-engrasado de fábrica.' WHERE id=52;
UPDATE productos SET marca='Motul',        codigo_barras='3374650048003', proveedor='Europarts Iberia SA', ubicacion='Estante B-3', descripcion_larga='Aceite 100% sintético Motul 7100 10W-40 4T. Tecnología ester para protección total. JASO MA2, API SN. Compatible con embragues húmedos. Garrafa 4 litros. Cambio cada 5.000–7.000 km.' WHERE id=53;
UPDATE productos SET marca='Repsol',       codigo_barras='8414956016284', proveedor='Europarts Iberia SA', ubicacion='Estante B-3', descripcion_larga='Aceite Repsol Moto Racing 4T 10W-40 100% sintético. Tecnología POLI-ALPHA-OLEFIN. JASO MA2. Reduce fricción interna hasta 20%. 4 litros. Aceite oficial equipo Repsol Honda MotoGP.' WHERE id=54;
UPDATE productos SET marca='Castrol',      codigo_barras='3383420044832', proveedor='Europarts Iberia SA', ubicacion='Estante B-3', descripcion_larga='Aceite 2T Castrol Power 1 TTS 100% sintético. Tecnología TRIZONE. Mezcla 1:50. 1 litro. Excelente para scooters de alto rendimiento y motores 2T de competición.' WHERE id=55;
UPDATE productos SET marca='NGK',          codigo_barras='0070043117003', proveedor='Europarts Iberia SA', ubicacion='Estante B-2', descripcion_larga='Bujía estándar NGK CR9EK de cobre. Rosca M14x1,25. Llave 16 mm. Tipo resistivo para encendido electrónico. Compatible con Kawasaki ZX-6R y Honda CBR600RR. Vida útil: 15.000 km.' WHERE id=56;
UPDATE productos SET marca='Denso',        codigo_barras='0019111172252', proveedor='Europarts Iberia SA', ubicacion='Estante B-2', descripcion_larga='Bujía Denso IU22 Iridium Power. Punta iridio 0,4 mm. Electrodo lateral platino. Compatible con Honda, Yamaha y Suzuki. Mejor throttle response vs bujía estándar. Vida útil: 60.000 km.' WHERE id=57;
UPDATE productos SET marca='Athena',       codigo_barras='8002462175503', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Kit juntas motor Kawasaki ZX636 (2003–2006). Incluye todas las juntas de tapa válvulas, tapa embrague, Carter, base cilindro y culata. Material: grafito y elastómero. Resistente hasta 300 °C.' WHERE id=58;
UPDATE productos SET marca='Gates',        codigo_barras='5414465310571', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Correa distribución Gates Honda CBF 125 (NF125). Polímero alto módulo reforzado con kevlar. Paso 8 mm, 86 dientes. Cambio recomendado cada 20.000 km o 2 años.' WHERE id=59;
UPDATE productos SET marca='Genérico',     codigo_barras='8412345101069', proveedor='Europarts Iberia SA', ubicacion='Estante B-1', descripcion_larga='Filtro combustible universal para manguera 6 mm. Filtrado 10 µm. Elemento papel en carcasa aluminio. Compatible con gasolina y mezclas E10. Cambio cada 10.000 km.' WHERE id=60;
UPDATE productos SET marca='Piaggio OEM',  codigo_barras='8004815099418', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Válvula admisión Vespa GTS 125 ie (motores LEADER). Diámetro cabeza: 26 mm. Acero inoxidable X45CrSi93. Referencia Piaggio: 9510015.' WHERE id=61;
UPDATE productos SET marca='Athena',       codigo_barras='8002462195816', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Junta culata Honda CB500F (PC45, 2013–2015). Multicapa acero MLS 0,65 mm. Diámetro cilindro: 67 mm. Resistente hasta 400 °C y 130 bar. No requiere retorqueo tras rodaje.' WHERE id=62;
UPDATE productos SET marca='Suzuki OEM',   codigo_barras='8401234567891', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Termostato motor Suzuki GSX-R 600/750 K1–K5 (2001–2005). Apertura: 80 °C. Apertura completa: 95 °C. Alojamiento bronce. Referencia OEM 17670-38F20.' WHERE id=63;
UPDATE productos SET marca='Honda OEM',    codigo_barras='4547764819119', proveedor='Europarts Iberia SA', ubicacion='Estante B-4', descripcion_larga='Sensor temperatura agua Honda CB1000R SC60 (2008–2017). Conector negro 2 pines. Rango: -40 a +130 °C. Referencia OEM 37870-MBA-003. Controla cuadro e instrumentos y ventilador.' WHERE id=64;

-- ── TRANSMISIÓN (Estante C) ───────────────────────────────────────────────────
UPDATE productos SET marca='DID',              codigo_barras='4961325001107', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Kit cadena DID 520 VX3 Gold con X-Ring dorados. Incluye cadena 120 eslabones, eslabón clip y 2 retenes. Carga de rotura: 32 kN. Ideal para 600 cc supersport.' WHERE id=6;
UPDATE productos SET marca='JT Sprockets',     codigo_barras='8431369012007', proveedor='TwoWheels Supply SL', ubicacion='Estante C-2', descripcion_larga='Piñón conductor 15T acero cementado. Paso 520. Hexágono interno 17 mm. Compatible con motores 125–400 cc de varias marcas. Apriete: 65 Nm.' WHERE id=7;
UPDATE productos SET marca='DID',              codigo_barras='4961325002005', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Cadena DID 520 ERV3 Gold Race. Eslabones forjados Duraflex. X-Ring sellado con grasa molibdeno. 110 eslabones. Carga de rotura: 34 kN. Uso en pista o sport road.' WHERE id=65;
UPDATE productos SET marca='RK Excel',         codigo_barras='4912019020012', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Cadena RK 525 GXW con XW-Ring. Junta cuádruple para mínima pérdida por fricción. 110 eslabones. Carga de rotura: 36,1 kN. Compatible con motores 600–1000 cc paso 525.' WHERE id=66;
UPDATE productos SET marca='DID / JT Sprockets', codigo_barras='4961325003001', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Kit transmisión Yamaha MT-07 2014–2020. Cadena DID 525 VX3 Gold 116 eslabones, piñón JT 16T y corona JT 43T. Duración estimada: 20.000 km con mantenimiento correcto.' WHERE id=67;
UPDATE productos SET marca='DID / JT Sprockets', codigo_barras='4961325003002', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Kit transmisión Kawasaki Z900 2017–2022. Cadena DID 525 ZVM-X 116 eslabones, piñón JT 15T y corona JT 41T. Ajustado a especificaciones OEM. Duración estimada: 20.000–25.000 km.' WHERE id=68;
UPDATE productos SET marca='Renthal',          codigo_barras='5025895141001', proveedor='TwoWheels Supply SL', ubicacion='Estante C-2', descripcion_larga='Corona Renthal aluminio 7075-T6. 42 dientes, paso 525. Anodizado rojo. Peso: 185 g vs 380 g acero. Compatible con cubos estándar 130 mm. Vida útil: 15.000 km con cadena nueva.' WHERE id=69;
UPDATE productos SET marca='JT Sprockets',     codigo_barras='8431369044503', proveedor='TwoWheels Supply SL', ubicacion='Estante C-2', descripcion_larga='Corona JT Sprockets acero 1045 tratado. 45 dientes, paso 520. Compatible con cubos 6 y 7 tornillos de 80 mm. Tratamiento anticorrosión por cadmio.' WHERE id=70;
UPDATE productos SET marca='JT Sprockets',     codigo_barras='8431369015008', proveedor='TwoWheels Supply SL', ubicacion='Estante C-2', descripcion_larga='Piñón delantero JT 16T paso 525. Acero 1045 cementado y templado. Compatible con Kawasaki, Suzuki y Yamaha 600–1000 cc. Apriete: 80 Nm.' WHERE id=71;
UPDATE productos SET marca='Genérico',         codigo_barras='8412345102516', proveedor='TwoWheels Supply SL', ubicacion='Estante C-2', descripcion_larga='Tensor cadena automático universal. Resorte acero y émbolo aluminio. Rosca M8x1,25. Evita holgura excesiva sin ajuste manual. Compatible con motores 50–200 cc.' WHERE id=72;
UPDATE productos SET marca='DID',              codigo_barras='4961325004008', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Eslabón unión rápida DID paso 520. Tipo clip con retén sellado. Color dorado. Incluye O-ring y grasa de montaje. Carga de rotura: 32 kN. Pack de 1 eslabón.' WHERE id=73;
UPDATE productos SET marca='RK Excel',         codigo_barras='4912019021019', proveedor='TwoWheels Supply SL', ubicacion='Estante C-1', descripcion_larga='Eslabón unión rápida RK paso 525. Tipo pasador con clip. X-Ring sellado. Carga de rotura: 36 kN. Compatible con cadenas RK 525 GXW, ZXW y ZXM. No reutilizable.' WHERE id=74;
UPDATE productos SET marca='Motul',            codigo_barras='3374650239305', proveedor='TwoWheels Supply SL', ubicacion='Estante C-3', descripcion_larga='Lubricante cadena Motul Chain Lube Road. Spray 400 ml con PTFE. Resistente al agua. No mancha rueda ni carenado. Aplicar sobre cadena caliente cada 500–1000 km.' WHERE id=75;
UPDATE productos SET marca='Castrol',          codigo_barras='4008177027390', proveedor='TwoWheels Supply SL', ubicacion='Estante C-3', descripcion_larga='Lubricante cadena Castrol Off-Road para barro y humedad extrema. Spray 400 ml con alta adherencia. Penetra en rodillos y retenes X/O-ring. Reaplicar cada 300–500 km.' WHERE id=76;

-- ── ELECTRICIDAD (Estante D) ──────────────────────────────────────────────────
UPDATE productos SET marca='Genérico',          codigo_barras='8412345103001', proveedor='ElectroParts Moto SL', ubicacion='Estante D-1', descripcion_larga='Regulador-rectificador universal 12 V. Salida: 13,8–14,5 V. Máximo 15 A. Disipador aluminio. Conector 5 pines compatible con Yamaha, Honda y Suzuki.' WHERE id=8;
UPDATE productos SET marca='Yuasa',             codigo_barras='5050694082504', proveedor='ElectroParts Moto SL', ubicacion='Estante D-2', descripcion_larga='Batería Yuasa YTZ10S AGM sellada. 12 V / 8,6 Ah. CCA: 190 A. Sin mantenimiento. 150x87x93 mm. Compatible con Honda CBR600RR/1000RR, Yamaha R6/R1, Kawasaki ZX-6R.' WHERE id=9;
UPDATE productos SET marca='Genérico',          codigo_barras='8412345103209', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Kit 2 bombillas LED H4 6000 K / 55 W totales. Base P43t con casquillo aluminio. Incluye adaptadores canbus anti-error. Verificar compatibilidad con reflector antes de instalar.' WHERE id=11;
UPDATE productos SET marca='Yuasa',             codigo_barras='5050694082207', proveedor='ElectroParts Moto SL', ubicacion='Estante D-2', descripcion_larga='Batería Yuasa YTX9-BS AGM sin mantenimiento. 12 V / 8 Ah. CCA: 120 A. 150x87x105 mm. Compatible con Honda CBR600F/900RR, Kawasaki Z750/Z1000. Entregada cargada. Vida: 3–5 años.' WHERE id=77;
UPDATE productos SET marca='Bosch',             codigo_barras='3165143093405', proveedor='ElectroParts Moto SL', ubicacion='Estante D-2', descripcion_larga='Batería Bosch M6 YTZ14S AGM. 12 V / 11,2 Ah. CCA: 200 A. Placa enrollada alta densidad. 150x87x110 mm. Compatible con Honda CB1000R, Yamaha MT-09, Kawasaki Z1000 y Ducati Multistrada.' WHERE id=78;
UPDATE productos SET marca='TecMate (Optimate)', codigo_barras='5420034870058', proveedor='ElectroParts Moto SL', ubicacion='Estante D-2', descripcion_larga='Cargador Optimate 4 Dual. 8 etapas automáticas. Compatible con AGM, GEL, estándar y litio LiFePO4. 12 V / 0,8 A. Indicador LED de estado de carga. Cable incluido.' WHERE id=79;
UPDATE productos SET marca='Osram',             codigo_barras='4008321411426', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Bombilla halógena Osram Night Breaker 200 H7. Hasta 200% más luz vs estándar. 12 V / 55 W. Casquillo PX26d. Temperatura: 3900 K. Homologada ECE. Vida útil: 150 h.' WHERE id=80;
UPDATE productos SET marca='Philips',           codigo_barras='8711559666074', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Bombilla Philips X-tremeVision Moto H4. 60/55 W. Hasta 130% más visibilidad. Temperatura: 3700 K. Casquillo P43t. Resistente a vibraciones de moto. Cumple R37/ECE.' WHERE id=81;
UPDATE productos SET marca='Osram',             codigo_barras='4062172162128', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Kit LED H7 Osram LEDriving HL Gen2. 2 bombillas 12 V / 15 W (equiv. 55 W halógeno). 6000 K. 1500 lm por bombilla. Canbus anti-error. Homologado ECE R37. Plug-and-play.' WHERE id=82;
UPDATE productos SET marca='Electrosport',      codigo_barras='0703938250038', proveedor='ElectroParts Moto SL', ubicacion='Estante D-1', descripcion_larga='Regulador-rectificador para Yamaha FZ6/FZS 600 Fazer 2004–2009. Salida regulada 14,2 V. Disipador mejorado. Conector plug-in. Soluciona sobrecalentamiento del regulador original.' WHERE id=83;
UPDATE productos SET marca='Genérico',          codigo_barras='8412345103407', proveedor='ElectroParts Moto SL', ubicacion='Estante D-1', descripcion_larga='Relé arranque universal 12 V / 30 A. 4 terminales. Bobina 12 V / 180 Ohm. Carcasa estanca IP54. Compatible con cualquier moto con arranque eléctrico 12 V.' WHERE id=84;
UPDATE productos SET marca='Kawasaki OEM',      codigo_barras='4054783060019', proveedor='ElectroParts Moto SL', ubicacion='Estante D-1', descripcion_larga='Bobina encendido para Kawasaki ER-6N/ER-6F 2006–2011. 12 V. Resistencia primario: 3 Ohm. Secundario: 10 kOhm. Conector 3 pines. Referencia OEM 21121-0013.' WHERE id=85;
UPDATE productos SET marca='Suzuki OEM',        codigo_barras='8401234568997', proveedor='ElectroParts Moto SL', ubicacion='Estante D-1', descripcion_larga='Sensor CKP Suzuki GSX-R1000 K7–K8 (2007–2008). Hall Effect. Conector 3 pines negro. Referencia OEM 32160-01H00. Fallo típico: motor se para sin aviso o no arranca en caliente.' WHERE id=86;
UPDATE productos SET marca='Koso',              codigo_barras='4713257832018', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Par intermitentes LED homologados ECE R6. Carcasa CNC negro. 12 V / 2 W. IP67. Rosca M10x1,25. Incluye resistencias canbus. Ángulo de emisión: 150 grados.' WHERE id=87;
UPDATE productos SET marca='NGK',               codigo_barras='0070043620026', proveedor='ElectroParts Moto SL', ubicacion='Estante D-3', descripcion_larga='Set cables bujía NGK Racing RC-YM803 para Yamaha 4 cilindros. Cable 8 mm silicona con trenzado metálico anti-RFI. Resistente hasta 220 °C. Mejora encendido en altas rpm.' WHERE id=88;
UPDATE productos SET marca='Genérico',          codigo_barras='8412345103605', proveedor='ElectroParts Moto SL', ubicacion='Estante D-4', descripcion_larga='Pack 10 fusibles cuchilla mini 10 A. Color rojo. Tipo ATC/ATM 10 A / 32 V. Compatibles con portas estándar japoneses y europeos.' WHERE id=89;
UPDATE productos SET marca='Genérico',          codigo_barras='8412345103803', proveedor='ElectroParts Moto SL', ubicacion='Estante D-4', descripcion_larga='Interruptor emergencia universal para moto. Desconecta encendido de inmediato. Botón seta con enclavamiento. IP54. 12 V / 10 A. Montaje en manillar o carenado mediante abrazadera.' WHERE id=90;

-- ── CARROCERÍA (Estante E / Almacén) ─────────────────────────────────────────
UPDATE productos SET marca='Aftermarket',  codigo_barras='8412345104008', proveedor='Carrocerías y Accesorios SL', ubicacion='Almacén Carrocería-A', descripcion_larga='Carenado lateral izquierdo Yamaha YZF-R6 (2017–2020). ABS alta resistencia prepintado blanco. Incluye todos los puntos de fijación OEM. Instalación profesional recomendada.' WHERE id=10;
UPDATE productos SET marca='Aftermarket',  codigo_barras='8412345104107', proveedor='Carrocerías y Accesorios SL', ubicacion='Almacén Carrocería-A', descripcion_larga='Carenado frontal Kawasaki ZX-6R (2007–2008). ABS alto impacto sin pintar. Tornillería OEM incluida. Compatible solo con modelos 636 cc de esos años.' WHERE id=91;
UPDATE productos SET marca='Aftermarket',  codigo_barras='8412345104206', proveedor='Carrocerías y Accesorios SL', ubicacion='Almacén Carrocería-A', descripcion_larga='Carenado bajo motor Yamaha YZF-R1 (2015–2019). ABS prepintado blanco. Diseño idéntico al original. Incluye clips de fijación inferiores y laterales.' WHERE id=92;
UPDATE productos SET marca='Aftermarket',  codigo_barras='8412345104305', proveedor='Carrocerías y Accesorios SL', ubicacion='Almacén Carrocería-A', descripcion_larga='Cola trasera Yamaha MT-09 (2017–2020). ABS sin pintar. Compatible con versiones Street y Tracer 900. Incluye portamatrículas original. Tornillería OEM directa.' WHERE id=93;
UPDATE productos SET marca='CNC Racing',   codigo_barras='8012719015010', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-1', descripcion_larga='Retrovisor CNC aluminio 7075 plegable. Brazo ajustable en 3 posiciones. Espejo convexo 85x55 mm. Rosca M10 inversa. Homologado ECE R46. Compatible con manillares 7/8 pulgadas.' WHERE id=94;
UPDATE productos SET marca='Honda OEM',    codigo_barras='4547764551318', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-1', descripcion_larga='Par retrovisores OEM Honda CB650R (2019–2022). Cristal esférico 95x65 mm. Rosca derecha e izquierda. Refs: 88110-MKN-D01 (derecho) y 88120-MKN-D01 (izquierdo).' WHERE id=95;
UPDATE productos SET marca='Renthal',      codigo_barras='5025895100107', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-2', descripcion_larga='Manillar Renthal Fatbar 28 mm aluminio 7075 negro. Alzada 80 mm, anchura 800 mm, retroceso 5 grados. Gomas antivibratorias incluidas. Compatible con risers de 28 mm. Peso: 580 g.' WHERE id=96;
UPDATE productos SET marca='Oxford',       codigo_barras='5030009006019', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-2', descripcion_larga='Puños Oxford Primo espuma alta densidad. Diámetro interior: 22 mm. Longitud: 130 mm. Patrón hexagonal antideslizante. Fijación por adhesivo. Par incluido.' WHERE id=97;
UPDATE productos SET marca='Oxford',       codigo_barras='5030009016018', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-2', descripcion_larga='Puños calefactables Oxford Hot Grips Essential para manillar 22 mm. 18 W (alta) / 12 W (baja). 12 V / 1,5 A. Temperatura máxima: 48 °C. Controlador integrado. Instalación en 45 min.' WHERE id=98;
UPDATE productos SET marca='Genérico',     codigo_barras='8412345104908', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-3', descripcion_larga='Protector depósito resina epoxi transparente autoadhesivo con refuerzo aramídico. Grosor: 0,3 mm. Medidas: 20x30 cm recortable. Aplica con calor para moldear.' WHERE id=99;
UPDATE productos SET marca='Rizoma',       codigo_barras='8032532219017', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-1', descripcion_larga='Tapa depósito CNC aluminio aeronáutico para Ducati Monster 821 (2014–2020) y Monster 1200 (2014–2021). Anodizado negro. Apertura 90 grados. Válvula de ventilación integrada.' WHERE id=100;
UPDATE productos SET marca='Genérico',     codigo_barras='8412345105103', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-3', descripcion_larga='Guardabarros trasero corto tipo racing en ABS negro. Compatible con ruedas 180/55 y 190/55 en llanta 17 pulgadas. Montaje con 2 tornillos M8. Longitud: 22 cm.' WHERE id=101;
UPDATE productos SET marca='Aftermarket',  codigo_barras='8412345105202', proveedor='Carrocerías y Accesorios SL', ubicacion='Almacén Carrocería-B', descripcion_larga='Pasarruedas trasero Suzuki GSX-R 600/750 (2006–2010). ABS negro sin pintar. Incluye toma de aire para ventilación del disco trasero. Verificar año exacto antes de instalar.' WHERE id=102;
UPDATE productos SET marca='Genérico',     codigo_barras='8412345105400', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-4', descripcion_larga='Kit tornillería carenado acero inoxidable A2. 30 piezas: tornillos M5x10, M6x12 y M6x20 con arandela y tuerca autoblocante. Cabeza botón ISO 7380 para bajo perfil.' WHERE id=103;
UPDATE productos SET marca='Genérico',     codigo_barras='8412345105509', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-4', descripcion_larga='Cinta antivibración espuma poliuretano doble cara. Grosor: 5 mm. Rollo 50x500 mm. Temperatura: -20 a +90 °C. Imprescindible para evitar chirridos en carenados de repuesto.' WHERE id=104;
UPDATE productos SET marca='Saddlemen',    codigo_barras='0818485011017', proveedor='Carrocerías y Accesorios SL', ubicacion='Estante E-1', descripcion_larga='Asiento custom Saddlemen Honda CB750 Nighthawk (1991–2003). Espuma alta densidad con piel sintética negra. Altura reducida 30 mm vs original. Sin modificaciones en subchasis. Peso: 1,2 kg.' WHERE id=105;

SELECT CONCAT('Actualizados: ', COUNT(*), ' productos') AS resultado FROM productos WHERE marca IS NOT NULL AND deleted_at IS NULL;
